- name: Install Docker packages
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ role_app_docker_packages }}'

- name: Enable and start docker service
  service:
    name: '{{ role_app_docker_service }}'
    state: started
    enabled: yes
